import pandas as pd

def map_varieties(input_variety=None):

    grape_varieties = {
        "Cabernet Sauvignon": "red",
        "Tinta de Toro": "red",  # Similar to Tempranillo
        "Sauvignon Blanc": "white",
        "Pinot Noir": "red",
        "Provence red blend": "red",
        "Friulano": "white",  # Formerly known as Tocai Friulano, a white wine grape
        "Tannat": "red",
        "Chardonnay": "white",
        "Tempranillo": "red",
        "Malbec": "red",
        "Rosé": "rose",
        "Tempranillo Blend": "red",
        "Syrah": "red",
        "Mavrud": "red",  # A Bulgarian red wine grape
        "Sangiovese": "red",
        "Sparkling Blend": "white",  # Often used for white sparkling wines
        "Rhône-style White Blend": "white",
        "Red Blend": "red",
        "Mencía": "red",
        "Palomino": "white",  # Used in Sherry, a white wine
        "Petite Sirah": "red",
        "Riesling": "white",
        "Cabernet Sauvignon-Syrah": "red",
        "Portuguese Red": "red",
        "Nebbiolo": "red",
        "Pinot Gris": "white",
        "Meritage": "red",  # Typically a Bordeaux-style blend, red
        "Baga": "red",
        "Glera": "white",  # Primarily used for Prosecco
        "Malbec-Merlot": "red",
        "Merlot-Malbec": "red",
        "Ugni Blanc-Colombard": "white",  # Commonly used for white wines and brandy
        "Viognier": "white",
        "Cabernet Sauvignon-Cabernet Franc": "red",
        "Moscato": "white",
        "Pinot Grigio": "white",
        "Cabernet Franc": "red",
        "White Blend": "white",
        "Monastrell": "red",  # Known as Mourvèdre, typically red
        "Gamay": "red",
        "Zinfandel": "red",
        "Greco": "white",  # Greco is typically used for white wines in Italy
        "Barbera": "red",
        "Grenache": "red",
        "Rhône-style Red Blend": "red",
        "Albariño": "white",
        "Malvasia Bianca": "white",
        "Assyrtiko": "white",
        "Malagouzia": "white",
        "Carmenère": "red",
        "Bordeaux-style Red Blend": "red",
        "Touriga Nacional": "red",
        "Agiorgitiko": "red",
        "Picpoul": "white",  # Picpoul Blanc
        "Godello": "white",
        "Gewürztraminer": "white",
        "Merlot": "red",
        "Syrah-Grenache": "red",
        "G-S-M": "red",  # Grenache-Syrah-Mourvèdre blend
        "Mourvèdre": "red",
        "Bordeaux-style White Blend": "white",
        "Petit Verdot": "red",
        "Muscat": "white",  # Typically used for sweet white wines
        "Chenin Blanc-Chardonnay": "white",
        "Cabernet Sauvignon-Merlot": "red",
        "Pinot Bianco": "white",
        "Alvarinho": "white",
        "Portuguese White": "white",
        "Garganega": "white",
        "Sauvignon": "white",  # Assuming Sauvignon Blanc
        "Gros and Petit Manseng": "white",
        "Tannat-Cabernet": "red",
        "Alicante Bouschet": "red",
        "Aragonês": "red",  # Known as Tempranillo in Spain, typically red
        "Silvaner": "white",
        "Ugni Blanc": "white",  # Known for use in Cognac and white wines
        "Grüner Veltliner": "white",
        "Frappato": "red",
        "Lemberger": "red",  # Known as Blaufränkisch, typically red
        "Sylvaner": "white",
        "Chasselas": "white",
        "Alsace white blend": "white",
        "Früburgunder": "red",  # Early ripening Pinot Noir
        "Kekfrankos": "red",  # Known as Blaufränkisch
        "Vermentino": "white",
        "Sherry": "white",  # Typically a fortified white wine
        "Aglianico": "red",
        "Torrontés": "white",
        "Primitivo": "red",  # Known as Zinfandel in the USA
        "Semillon-Sauvignon Blanc": "white",
        "Portuguese Rosé": "rose",
        "Grenache-Syrah": "red",
        "Prié Blanc": "white",
        "Negrette": "red",
        "Furmint": "white",  # Mostly used for Hungarian white wines
        "Carignane": "red",
        "Pinot Blanc": "white",
        "Nero d'Avola": "red",
        "St. Laurent": "red",
        "Blauburgunder": "red",  # Known as Pinot Noir
        "Blaufränkisch": "red",
        "Scheurebe": "white",
        "Ribolla Gialla": "white",
        "Charbono": "red",
        "Malbec-Cabernet Sauvignon": "red",
        "Pinot Noir-Gamay": "red",
        "Pinot Nero": "red",  # Italian Pinot Noir
        "Gros Manseng": "white",
        "Nerello Mascalese": "red",
        "Shiraz": "red",
        "Negroamaro": "red",
        "Champagne Blend": "white",  # Typically used in white Champagne
        "Romorantin": "white",
        "Syrah-Cabernet Sauvignon": "red",
        "Tannat-Merlot": "red",
        "Duras": "red",
        "Garnacha": "red",
        "Tinta Francisca": "red",
        "Portuguese Sparkling": "white",
        "Chenin Blanc": "white",
        "Turbiana": "white",
        "Petite Verdot": "red",
        "Posip": "white",
        "Fumé Blanc": "white",  # Sauvignon Blanc, often oaked
        "Roussanne": "white",
        "Grillo": "white",
        "Müller-Thurgau": "white",
        "Pinot Auxerrois": "white",
        "Port": "red",  # Typically red, fortified
        "Cabernet Blend": "red",
        "Cabernet Franc-Cabernet Sauvignon": "red",
        "Castelão": "red",
        "Encruzado": "white",
        "Touriga Nacional-Cabernet Sauvignon": "red",
        "Colombard-Sauvignon Blanc": "white",
        "Moscatel": "white",  # Typically sweet white
        "Marsanne": "white",
        "Siria": "white",
        "Garnacha Blanca": "white",
        "Merlot-Cabernet Sauvignon": "red",
        "Arinto": "white",
        "Petit Manseng": "white",
        "Loureiro": "white",
        "Melon": "white",  # Often Melon de Bourgogne, used in Muscadet
        "Carricante": "white",
        "Fiano": "white",
        "Schwartzriesling": "red",  # Known as Pinot Meunier
        "Sangiovese-Syrah": "red",
        "Tannat-Cabernet Franc": "red",
        "Cabernet Franc-Merlot": "red",
        "Sauvignon Blanc-Semillon": "white",
        "Macabeo": "white",
        "Alfrocheiro": "red",
        "Aligoté": "white",
        "Verdejo": "white",
        "Grenache Blanc": "white",
        "Fernão Pires": "white",
        "Spätburgunder": "red",  # German Pinot Noir
        "Ciliegiolo": "red",
        "Cabernet Sauvignon-Carmenère": "red",
        "Auxerrois": "white",
        "Sirica": "red",
        "Zweigelt": "red",
        "Pugnitello": "red",
        "Rosado": "rose",
        "Rosato": "rose",
        "Malvazija": "white",
        "Kalecik Karasi": "red",
        "Muskat Ottonel": "white",
        "Malbec-Bonarda": "red",
        "Tempranillo-Cabernet Sauvignon": "red",
        "Rivaner": "white",  # Another name for Müller-Thurgau
        "Trepat": "red",
        "Baco Noir": "red",
        "Trebbiano": "white",
        "Chardonnay-Viognier": "white",
        "Syrah-Mourvèdre": "red",
        "Graciano": "red",
        "Roviello": "red",  # Assuming this is a red variety
        "Perricone": "red",
        "Falanghina": "white",
        "Vranec": "red",
        "Carignan": "red",
        "Cabernet-Shiraz": "red",
        "Verdelho": "white",
        "Pedro Ximénez": "white",  # Often used for sweet white sherry
        "Marsanne-Roussanne": "white",
        "Malbec Blend": "red",
        "Weissburgunder": "white",  # Another name for Pinot Blanc
        "Morava": "white",  # Assuming a white variety
        "Ruen": "red",  # Assuming a red variety
        "Hondarrabi Zuri": "white",
        "Catarratto": "white",
        "Chardonnay-Sauvignon Blanc": "white",
        "Vidal": "white",
        "Rieslaner": "white",
        "Dornfelder": "red",
        "Tinto Fino": "red",  # Synonym for Tempranillo
        "Gelber Muskateller": "white",
        "Roter Veltliner": "white",
        "Aragonez": "red",  # Another name for Tempranillo
        "Vitovska": "white",
        "Pinot Noir-Syrah": "red",
        "Gamay Noir": "red",
        "Grauburgunder": "white",  # Another name for Pinot Gris
        "Cannonau": "red",  # Sardinian name for Grenache
        "Mauzac": "white",
        "Austrian Red Blend": "red",
        "Sémillon": "white",
        "Lambrusco di Sorbara": "red",  # Usually light red sparkling wines
        "Teran": "red",
        "Dolcetto": "red",
        "Cinsault": "red",
        "Assyrtico": "white",
        "Teroldego": "red",
        "Tamjanika": "white",  # Assuming a white variety
        "Boğazkere": "red",
        "Kadarka": "red",
        "Narince": "white",
        "Malbec-Petit Verdot": "red",
        "Veltliner": "white",  # Grüner Veltliner is white
        "Traminer": "white",  # Often Gewürztraminer, a white variety
        "Lambrusco": "red",
        "Arneis": "white",
        "Cabernet Sauvignon-Shiraz": "red",
        "Tocai Friulano": "white",
        "Fer Servadou": "red",
        "Muskateller": "white",
        "Nerello Cappuccio": "red",
        "Moscatel Roxo": "red",  # A rare red-skinned variety of Muscat
        "Elbling": "white",
        "Saperavi": "red",
        "Antão Vaz": "white",
        "Pinot Meunier": "red",  # Common in Champagne, typically red
        "Petite Syrah": "red",
        "Malvasia": "white",  # Often white, but can vary
        "Malbec-Tannat": "red",
        "Kallmet": "red",
        "Syrah-Merlot": "red",
        "Montepulciano": "red",
        "Kerner": "white",
        "Alvarinho-Chardonnay": "white",
        "Žilavka": "white",  # Assuming a white variety
        "Vinhão": "red",  # Known as Vinhão in Vinho Verde, typically red
        "Chardonnay-Semillon": "white",
        "Carmenère-Cabernet Sauvignon": "red",
        "Merlot-Cabernet Franc": "red",
        "Orangetraube": "white",
        "Cabernet Sauvignon-Sangiovese": "red",
        "Okuzgozu": "red",
        "Viura": "white",
        "Garnacha-Syrah": "red",
        "Zibibbo": "white",  # A Muscat variety, often used for sweet white wines
        "Feteasca": "white",  # Assuming Fetească Albă, a white variety
        "Xarel-lo": "white",
        "Prokupac": "red",
        "Códega do Larinho": "white",
        "Touriga Nacional Blend": "red",
        "Inzolia": "white",
        "Cabernet-Syrah": "red",
        "Lambrusco Grasparossa": "red",
        "Malagousia": "white",
        "Cabernet Franc-Malbec": "red",
        "Feteasca Neagra": "red",
        "Yapincak": "white",
        "Tempranillo-Shiraz": "red",
        "Cabernet Sauvignon Grenache": "red",
        "Tinta Roriz": "red",  # Known as Tempranillo in Spain
        "Merlot-Syrah": "red",
        "Tinta Fina": "red",  # Another name for Tempranillo
        "Colombard-Ugni Blanc": "white",
        "Colombard": "white",
        "Roditis": "white",
        "Grenache-Carignan": "red",
        "Emir": "white",
        "Orange Muscat": "white",
        "Karalahna": "red",
        "Trincadeira": "red",
        "Refosco": "red",
        "Pied de Perdrix": "red",  # A style of light red wine
        "Vignoles": "white",
        "Carignan-Grenache": "red",
        "Muscat d'Alexandrie": "white",
        "Bobal": "red",
        "Symphony": "white",
        "Norton": "red",
        "Sauvignon Blanc-Sauvignon Gris": "white",
        "Rkatsiteli": "white",
        "Roussanne-Viognier": "white",
        "Pinela": "white",
        "Blatina": "red",
        "Shiraz-Viognier": "red",
        "Bonarda": "red",  # Known as Charbono in California
        "Sauvignon Blanc-Chardonnay": "white",
        "Chambourcin": "red",
        "Traminette": "white",
        "Grenache Blend": "red",
        "Jaen": "red",
        "Mondeuse": "red",
        "Feteascǎ Regalǎ": "white",
        "Teroldego Rotaliano": "red",
        "Sangiovese-Cabernet Sauvignon": "red",
        "Listán Negro": "red",
        "Syrah-Petite Sirah": "red",
        "Viognier-Chardonnay": "white",
        "Kuntra": "red",
        "Jacquère": "white",
        "Portuguiser": "red",
        "Grecanico": "white",
        "Verdejo-Viura": "white",
        "Tinto del Pais": "red",  # Another name for Tempranillo
        "Moscato Giallo": "white",
        "Cabernet Sauvignon-Malbec": "red",
        "Mission": "red",
        "Neuburger": "white",
        "Bastardo": "red",
        "Bical": "white",
        "Sacy": "white",
        "Carineña": "red",
        "Garnacha-Tempranillo": "red",
        "Pecorino": "white",
        "Garnacha Blend": "red",
        "Cococciola": "white",
        "Passerina": "white",
        "Gaglioppo": "red",
        "Garnacha Tintorera": "red",
        "Prieto Picudo": "red",
        "Tempranillo Blanco": "white",
        "Cesanese d'Affile": "red",
        "Muscat Canelli": "white",
        "Cabernet": "red",  # Likely Cabernet Sauvignon
        "Malvasia Nera": "red",
        "Premsal": "white",
        "Mansois": "red",
        "Welschriesling": "white",
        "Shiraz-Tempranillo": "red",
        "Verdicchio": "white",
        "Sagrantino": "red",
        "Rolle": "white",  # Another name for Vermentino
        "Trousseau Gris": "white",
        "Counoise": "red",
        "Mantonico": "white",
        "Cariñena-Garnacha": "red",
        "Insolia": "white",
        "Tokaji": "white",  # Used in Hungarian Tokaji, often sweet
        "Austrian white blend": "white",
        "Shiraz-Grenache": "red",
        "Claret": "red",  # British term for Bordeaux-style red blend
        "Syrah-Tempranillo": "red",
        "Uva di Troia": "red",
        "Aleatico": "red",
        "Piedirosso": "red",
        "Viognier-Marsanne": "white",
        "Pinot Grigio-Sauvignon Blanc": "white",
        "Pallagrello Nero": "red",
        "Chardonnay-Albariño": "white",
        "Savagnin": "white",
        "Pinotage": "red",
        "Braucol": "red",
        "Moschofilero": "white",
        "Nero di Troia": "red",
        "Carignano": "red",
        "Susumaniello": "red",
        "Baga-Touriga Nacional": "red",
        "Vidal Blanc": "white",
        "Vernaccia": "white",
        "Corvina, Rondinella, Molinara": "red",  # Used in Valpolicella blend
        "Mavrotragano": "red",
        "Garnacha-Monastrell": "red",
        "Lagrein": "red",
        "Cabernet Merlot": "red",  # Likely a blend of Cabernet and Merlot
        "Monastrell-Syrah": "red",
        "Malbec-Tempranillo": "red",
        "Syrah-Viognier": "red",
        "Verdeca": "white",
        "Sangiovese Grosso": "red",
        "Merlot-Argaman": "red",
        "Chenin Blanc-Viognier": "white",
        "Garnacha-Cabernet": "red",
        "Maturana": "red",
        "Malvar": "white",
        "Airen": "white",
        "Monica": "red",
        "Gewürztraminer-Riesling": "white",
        "Prugnolo Gentile": "red",  # Clone of Sangiovese
        "Steen": "white",  # Another name for Chenin Blanc
        "Chenin Blanc-Sauvignon Blanc": "white",
        "Shiraz-Cabernet Sauvignon": "red",
        "Picolit": "white",
        "Prosecco": "white",
        "White Riesling": "white",
        "White Port": "white",
        "Zierfandler": "white",
        "Petroulianos": "unknown",  # Not enough information
        "Mavrodaphne": "red",
        "Savatiano": "white",
        "Tempranillo-Garnacha": "red",
        "Vidadillo": "red",
        "Syrah-Cabernet": "red",
        "Gelber Traminer": "white",
        "Grenache-Shiraz": "red",
        "Rotgipfler": "white",
        "Cabernet Sauvignon-Tempranillo": "red",
        "Edelzwicker": "white",  # Alsatian white blend
        "Cortese": "white",
        "Chardonnay Weissburgunder": "white",  # Weissburgunder is Pinot Blanc
        "Torbato": "white",
        "Verduzzo": "white",  # Often used in sweet white wines
        "Debit": "white",
        "Bovale": "red",
        "Tempranillo-Merlot": "red",
        "Xinisteri": "white",
        "Merlot-Cabernet": "red",
        "Verdejo-Sauvignon Blanc": "white",
        "Black Muscat": "red",  # A Muscat variety used for red wines
        "Koshu": "white",
        "Királyleányka": "white",
        "Favorita": "white",  # Another name for Vermentino
        "Xinomavro": "red",
        "Cserszegi Fűszeres": "white",
        "Hárslevelü": "white",
        "Pallagrello": "unknown",  # Insufficient information
        "Mavroudi": "red",
        "Muscat Blanc": "white",
        "Schiava": "red",
        "Meoru": "unknown",  # Insufficient information
        "Nuragus": "white",
        "Trebbiano di Lugana": "white",  # A variety of Trebbiano
        "Coda di Volpe": "white",
        "Raboso": "red",
        "Shiraz-Pinotage": "red",
        "Enantio": "red",
        "Greco Bianco": "white",
        "Tai": "white",
        "Tokay": "white",  # Assuming Tokay Pinot Gris
        "Muscadel": "white",  # Sweet wine grape, often white
        "Cabernet Franc-Carmenère": "red",
        "Tintilia ": "red",
        "Segalin": "unknown",  # Not enough information
        "Lacrima": "red",
        "Cerceal": "white",
        "Cayuga": "white",
        "Sauvignon Gris": "white",
        "Albana": "white",
        "Corvina": "red",  # Typically used in Valpolicella
        "Macabeo-Moscatel": "white",
        "Macabeo-Chardonnay": "white",
        "Moscadello": "white",
        "Nasco": "white",
        "Viognier-Roussanne": "white",
        "Plavac Mali": "red",
        "Cabernet Sauvignon-Merlot-Shiraz": "red",
        "Sauvignon Blanc-Chenin Blanc": "white",
        "Shiraz-Mourvèdre": "red",
        "Albarín": "white",
        "Black Monukka": "unknown",  # Not enough information
        "Morio Muskat": "white",
        "Nielluciu": "red",  # Corsican grape, similar to Sangiovese
        "Alicante": "red",
        "Cabernet Sauvignon and Tinta Roriz": "red",
        "Viura-Chardonnay": "white",
        "Loin de l'Oeil": "white",
        "Roter Traminer": "white",  # Another name for Gewürztraminer
        "Karasakiz": "red",
        "Casavecchia": "red",
        "Malvasia-Viura": "white",
        "Nosiola": "white",
        "Incrocio Manzoni": "white",
        "Viura-Verdejo": "white",
        "Erbaluce": "white",
        "Forcallà": "red",
        "Pansa Blanca": "white",
        "Catalanesca": "white",
        "Muscadelle": "white",
        "Malbec-Syrah": "red",
        "Petit Meslier": "white",
        "Johannisberg Riesling": "white",  # Another name for Riesling
        "Pignoletto": "white",
        "Cabernet Pfeffer": "red",
        "Syrah-Cabernet Franc": "red",
        "Valdiguié": "red",
        "Mazuelo": "red",  # Known as Carignan
        "Brachetto": "red",  # Typically used for sweet, fizzy red wines
        "Jacquez": "red",
        "Moscofilero": "white",
        "Chardonnay-Sauvignon": "white",
        "Madeleine Angevine": "white",
        "Ruché": "red",
        "Merlot-Petite Verdot": "red",
        "Roussanne-Marsanne": "white",
        "Moscatel de Alejandría": "white",
        "Muscat Blanc à Petit Grain": "white",
        "Sämling": "white",  # Another name for Scheurebe
        "Mtsvane": "white",
        "Zlahtina": "white",
        "Zelen": "white",
        "Doña Blanca": "white",
        "Carmenère-Syrah": "red",
        "Roussanne-Grenache Blanc": "white",
        "Kinali Yapincak": "white",
        "Robola": "white",
        "Pinot Blanc-Chardonnay": "white",
        "Chardonnay-Pinot Blanc": "white",
        "Saperavi-Merlot": "red",
        "Malvasia Istriana": "white",
        "Torontel": "white",
        "Picapoll": "white",
        "Zierfandler-Rotgipfler": "white",  # Typically used for Austrian white wines
        "Malvasia Fina": "white",
        "Chinuri": "white",
        "Muscatel": "white",
        "Sousão": "red",
        "Silvaner-Traminer": "white",
        "Syrah-Carignan": "red",
        "Bukettraube": "white",
        "Muskat": "white",
        "Argaman": "red",
        "Provence white blend": "white",
        "Touriga Franca": "red",
        "Morillon": "white",  # Chardonnay from Styria, Austria
        "Carignan-Syrah": "red",
        "Aidani": "white",
        "Viognier-Grenache Blanc": "white",
        "Albarossa": "red",
        "Sauvignon Blanc-Verdejo": "white",
        "Grenache-Mourvèdre": "red",
        "Tannat-Syrah": "red",
        "Seyval Blanc": "white",
        "Tocai Rosso": "red",
        "Pinot-Chardonnay": "white",
        "Moscatel Graúdo": "white",
        "Pigato": "white",
        "Siegerrebe": "white",
        "Bombino Bianco": "white",
        "Trebbiano-Malvasia": "white",
        "Magliocco": "red",
        "Verduzzo Friulano ": "white",
        "Vespaiolo": "white",
        "Marzemino": "red",
        "Tempranillo-Malbec": "red",
        "Crespiello": "unknown",  # Not enough information
        "Cabernet Franc-Tempranillo": "red",
        "Gouveio": "white",
        "Caprettone": "white",
        "Garnacha-Graciano": "red",
        "Mataro": "red",  # Another name for Mourvèdre
        "Pineau d'Aunis": "red",
        "Bual": "white",  # Typically used in Madeira wine
        "Sercial": "white",  # Used in Madeira wine
        "Moscato di Noto": "white",
        "Sauvignonasse": "white",
        "Madeira Blend": "white",  # Typically a blend of white grapes
        "St. George": "red",  # Likely Agiorgitiko
        "Rebula": "white",
        "Pallagrello Bianco": "white",
        "Vilana": "white",
        "Pelaverga Piccolo": "red",
        "Syrah-Grenache-Viognier": "red",
        "Alvarelhão": "red",
        "Durif": "red",  # Another name for Petite Sirah
        "Angevine": "white",
        "Semillon-Chardonnay": "white",
        "Pinot Blanc-Pinot Noir": "white",
        "Manzoni": "white",
        "Maréchal Foch": "red",
        "Blauer Portugieser": "red",
        "Tocai": "white",  # Assuming Tocai Friulano
        "Shiraz-Malbec": "red",
        "Cabernet Moravia": "red",
        "Espadeiro": "red",
        "País": "red",
        "Altesse": "white",
        "Avesso": "white",
        "Grignolino": "red",
        "Mandilaria": "red",
        "Freisa": "red",
        "Merlot-Shiraz": "red",
        "Dafni": "white",
        "Xynisteri": "white",
        "Grechetto": "white",
        "Roscetto": "white",
        "Sideritis": "white",
        "Pinotage-Merlot": "red",
        "Asprinio": "white",
        "Grolleau": "red",
        "Gragnano": "red",
        "Ansonica": "white",
        "Sangiovese Cabernet": "red",
        "Tinta Barroca": "red",
        "Syrah-Bonarda": "red",
        "Marsanne-Viognier": "white",
        "Azal": "white",
        "Durello": "white",
        "Syrah-Malbec": "red",
        "Malbec-Cabernet Franc": "red",
        "Franconia": "red",
        "Rufete": "red",
        "Parraleta": "unknown",  # Not enough information
        "St. Vincent": "unknown",  # Not enough information
        "Groppello": "red",
        "Athiri": "white",
        "Muscat of Alexandria": "white",
        "Malvoisie": "white",  # Often another name for Malvasia
        "Colorino": "red",
        "Merlot-Grenache": "red",
        "Terret Blanc": "white",
        "Chardonel": "white",
        "Macabeo-Gewürztraminer": "white",
        "Grenache Gris": "white",
        "Rabigato": "white",
        "Muscat Hamburg": "red",  # Also known as Black Muscat
        "Sarba": "white",
        "Irsai Oliver": "white",
        "Chardonnay-Pinot Gris": "white",
        "Vermentino Nero": "red"
    }

    grape_varieties = {key.strip().lower(): value for key, value in grape_varieties.items()}

    # I normalized the input grape variety due to errors I was receiving with capitalization

    def map_single_variety(variety):
        variety_normalized = variety.strip().lower()
        return grape_varieties.get(variety_normalized, 'unknown')

    if input_variety is not None:
        if isinstance(input_variety, pd.Series):
            # Map each element of the Series
            return input_variety.apply(map_single_variety)
        else:
            # Map a single variety
            return map_single_variety(input_variety)
    else:
        # Return a list of all variety keys
        return [key.title() for key in grape_varieties.keys()]
